---
title: "Gravity model-historical background"
output: html_notebook
---

## Historical Background

Human interaction, be it migration, urban daily travel, marriage, information flows, and so on, has fascinated scholars for ages, and has been of interest for planning purposes to decision makers for almost as long. The conceptual foundations of the study of human interaction date back to at least the 19th century, when HC Carey wrote (as quoted in McKean, 1870):

>> Man, the molecule of society, is the subject of Social Science...The great law of _Molecular Gravitation_ (is) the indispensable condition of the existence of the being known as man...The greater the number collected in a given space, the greater is the attractive force that is there exerted...Gravitation is here, as everywhere, in the direct ratio of the mass and the _inverse_ one of distance

The fundamental idea is an analogy to Newton's Law of Universal Gravitation, originally published in Philosophiæ Naturalis Principia Mathematica in 1687. Carrothers insight that similar principles as in physics could be at work in human interaction did not receive widespread attention, and it was only partially used by Ravenstein (1889) for the study of migration.

It was not until the 20th century that these ideas would be rediscovered. Here, again, there are parallel attributions, which vary by discipline. In this way, EC Young investigated in the 1920s the movement of farm people under the hypothesis that the relative volume of migration is proportional to the attractiveness of a destination and inversely proportional to the square of the distance to the destination. It is notable that Young introduced an empirical proportionallity factor in this formulation of interaction.

In the decade of the 1930s, economist WJ Reilly proposed a law of retail gravitation that explained the point of indifference for two retail sites in terms of the attractiveness of the sites (i.e., bigger sites are more attractive than smaller sites), and the distance to each, with consumers generally having a preference to travel shorter distances, other things being equal. Accordingly:

$$
\frac{P_1}{d_1^2} = \frac{P_2}{d_2^2}
$$
where $P_i$ is the attractiveness (i.e., size) of retail site $i$ and $d_i$ the distance from an arbitrary point to the retail site.

It is easy to see that if we disregard size, the relationship is:
$$
\frac{d_1}{d_2} = 1
$$

This partial representation of Reilly's hypothesis suggests a connection to Voronoi polygons, since the point of indifference will be on the boundary of the polygon, equidistant from the two sites. The full formulation, by extension, can be seen as an alternative way of expressing weighted Voronoi polygons.

Closer approximations to the expression of Carey where obtain shortly after these works.

Astrophysicist JQ Stewart in a series of papers published in the decades of 1940 and 1950 posited a series of principles for so-called social physics, from a rule of inverse distance variation for social influence (1941) to a principle of demographic gravitation (1948). It is this latter work that most explicitly argues for a model of human interaction based on the physical law and put the principle in the notation that we currently use.

Around the same time, sociologist GK Zipf published a series of papers testing regularities in the size of settlements, including what he termed the $\frac{P_1P_2}{D}$ hypothesis. The hypothesis was that movement between two communities with populations $P_1$ and $P_2$ separated by a shortest path of length $D$ is proportional to the ratio noted above. Zipf empirically showed that this regularity held for the case of intercity personal movement (1946), for goods movement by railways (1946), and information (1946).

In Stewart's formulation, the gravity model for human interaction became:
$$
F = \frac{(\mu_1 N_1)(\mu_2N_2)}{d_{12}^2}
$$
where $F$ is the force of attraction between two population, $N_i$ is the size of the population of settlement $i$, $\mu_i$ is the _molecular weight_ of individuals in settlement $i$, and $d_{ij}$ is the distance between settlements $i$ and $j$. In the writting of Stewart (1948, p. 34), the molecular weight "...of the "average American" is taken as unity. Presumably the molecular weight of an Australian aborigine, for example, is on this scale much less than one", which sounds now shockingly racist, but that can reflect the interest/ability of individuals to interact with others. For instance, the molecular weight could be purchasing parity, or reflect individual preferences for interaction.

Many elements of the social physics movement were later rejected by the social science, including the comparison to molecules and the value-ladden assumptions about the molecular weight of individuals. Nonetheless, the gravity model continues to be widely used today in many applications, and the reason for that is that even if we reject the existence of "Laws" for human behavior, as a heuristic it still has remarkable power to capture regularities in behavior.

The work of Alan Wilson (1969) was invaluable in providing a theoretical footing for spatial interaction models that did not depend on physical analogies, but instead was based on information theory. Wilson demonstrated how spatial interaction models could be derived based on the principle of entropy maximization, and how the gravity model is a particular case of entropy maximization.

In this seminar we will introduce the gravity model and we will introduce different modelling methodologies for its application.