---
title: "A family of accessibility measures: a proposal for the TRB 2025 Doctoral Research in Transportation Modeling and Travel Behavior Analysis Workshop"
format: pdf
bibliography: bibliography.bib
---

Applicant: Anastasia Soukhov, PhD Candidate (Transport Geography) in the School of Earth, Environment and Society at McMaster University

Doctoral supervisor: Antonio Paez, full professor in the School of Earth, Environment and Society at McMaster University

# Research Abstract (500 words)

The inquiry into people's interaction in space has been a popular subject of investigation for over a century. From as far back as @careyPrinciplesSocialScience1858's sentiments on _"man [being] the molecule of society [and their interaction being subject to] the direct ratio of the mass and the inverse one of distance"_ [pg. 41,43], the investigation has been coloured by these relationships between a pair of masses (e.g., quantity of people, opportunities, or other scales of mass), their separation distances, and some **proportionality constant** to yield some force of attraction, the features of Newton's Law of Universal Gravitation (1687).

Following this tradition with a focus on _potential_ attraction, the concept of accessibility was defined as the  _"potential of opportunities for interaction"_ in @hansen1959. The work of @hansen1959 proved to be highly-influential, with literature demonstrating a link between Hansen-type measures (i.e., a mass term x distance function, also known as gravity-based accessibility measures) and positive population-based-, sustainability- and economic- outcomes (though often at odds). Moreover, accessibility planning counters mobility-based planning by centering the potential for mobility, arguably the ulterior 'good' provided by transportation systems, not mobility itself. For this theoretical reason, Hansen-type measures are becoming an increasingly popular transportation planning instrument signaling that accessibility-based planning over mobility-based perspectives may be on the horizon. However, an important critique still stands in the way: the difficultly in interpreting the accessibility values themselves.

Notably, the Hansen-type model of today is missing a proportionality constant. The doctoral research hypothesizes that this omission is the source of interpretation difficulty, and can be remedied by drawing from related 'gravity-based' transportation literature. Related literature includes spatial interaction models (the gravity model) [@wilson1971] as it also traces back to the same early 20th century investigations as the accessibility concept [@carrothersHistoricalReviewGravity1956; @griggRavensteinLawsMigration1977]. Unlike the gravity-based accessibility measure, the gravity model still carries all the features of the Newtonian analogy (i.e., balancing factors (i.e, a proportionality constant), mass term 1, mass term 2, and distance function [@wilson1971]): a proportionality constant is crucial for retaining the output as a tangible unit. For the gravity model, which measures _interaction_, the output units are often the number of trips generated between an origin and destination. For accessibility, the doctoral research reckons the units are _potential_ interaction, and the output could be the number of opportunities that can be potentially interacted with from the origin to all destinations.

If selected, the applicant will introduce a family of accessibility measures in a similar vein as the "family of spatial interaction models" [@wilson1971] by specifying types of balancing factors, demonstrating simple synthetic examples, and visualizations using data using origin-destination employment flows for Toronto, Canada. Though the research is ongoing, the applicant intends to defend this academic year, the empirical data for use in this work is already published as an open R data package paper [@soukhovTTS2016RDataSet2023], and the singly-constrained and composite singly-constrained examples are fully developed with associated peer-reviewed publications [@paez2019; @soukhovIntroducingSpatialAvailability2023; @soukhovMultimodalSpatialAvailability2024].


# Letter of nomination

<!-- this first para is largely copy-paste from the letter you submitted to SSHRC-->
Over the past few decades, a tension has been brewing between the importance of transportation for society and the economy, and its impacts on environment and people. The focus of transportation planning has traditionally been on mobility (facilitating the ease of movement over increasingly large regions), which has led to congestion in metropolitan regions that are home to large populations. As a result, for all its benefits, transportation is increasingly a tool for inefficient, energy-intensive movement. Researchers in the field of transportation has been sounding the alarm, and urging a change of focus from mobility to accessibility, that is, the ease of reaching destinations or _the potential of opportunities for interactions_. Transportation, after all, is seldom an end in and of itself, but rather a means to reach meaningful destinations. 

This is why the development of accessibility planning practice is important; however, accessibility measures must be put in order. As mentioned in the research abstract, a significant barrier to the adoption of accessibility into planning has to do with the issue of unit interpretation. The described doctoral research hypothesises a solution to this interaction issue by bridging the spatial interaction modeling's balancing factor typology onto accessibility measures, to create a family of accessibility measures. In this way, the research can potentially be a highly significant and timely, especially since a deeper understanding of the outputs of _potential_ interaction is required to respond to the rapidly changing transportation and land-use in urban areas and beyond. 

Their anticipated graduate date is August 2025.
